### ISSUE TITLE
vagrant ssh auth error : Timed out while waiting for the machine to boot

### ISSUE THREAD

**Issue by mahmoudaghvami** [JustMcAfee/ConcolicAndroidWrapper#1]
Hi, I have tried to test your tool. But at the beginning steps when I installed vagrant and execute
"vagrant up" command, the vagrant stops at the line "default: SSH auth method: private key".
I have a Ubuntu16.04 running on VMware on top of a Win10. And I am trying to put CATE in ubuntu.
But running vagrant had problems in ubuntu.

![image](https://user-images.githubusercontent.com/13216089/32289874-5d6ad512-bf4d-11e7-9972-58845d7eeeab.png)

**Comment by JustMcAfee** [comment]
Development on this project has moved here: https://github.com/ConcolicAnalysisAndroid/ConcolicAnalysisForAndroid

They might have a better response and/or fix
